# Generated by Django 4.0.3 on 2022-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_order_alter_cartitem_options_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
            preserve_default=False,
        ),
    ]
